// async function wrapper() {
//     let promise = await new Promise((resolve, reject) => {
        


//     })
//     .catch(err => {throw err});

//     return promise
// }

// start()
// .then(result => console.log(result))
// .catch(err => console.error(err));